### PR TITLE
ENH: Bump to ITK v5.3.0 with reusable workflow

### LINKED ISSUE #41: Help with installation?
Hi!

I installed itk-spcn using pip, within a conda env with python=3.9.

However, when using the itk within the same environment, it does not work properly. I manage to import and read/write images. 

But when calling itk.structure_preserving_color_normalization_filter(). I get
AttributeError: PyCapsule_Import "_ITKCommonPython._C_API" is not valid

I get a similar outcome when trying itk.StructurePreservingColorNormalizationFilter.New()

There seems to be a problem with the installation of the python interface. I've wrapped my head around it and spent hours searching but can't figure out why this is happening. Any help would be greatly appreciated! Thank you!

### PR DESCRIPTION
**Pull request by tbirdso**
Bumps package version to reference ITK v5.3.0. Also consolidates CI testing in ITK reusable workflow for easier maintenance.

Closes https://github.com/InsightSoftwareConsortium/ITKColorNormalization/issues/41

### CODE REVIEW

**Comment by dzenanz** [comment]
I guess we need to update the copyright headers too:
```log
1/3 Test #1: StructurePreservingColorNormalizationKWStyleTest ......***Failed    0.01 sec
/home/runner/work/ITKColorNormalization/ITKColorNormalization/include/itkStructurePreservingColorNormalizationFilter.h:9: error: Header mismatch: ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKColorNormalization/ITKColorNormalization/include/itkStructurePreservingColorNormalizationFilter.hxx:9: error: Header mismatch: ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKColorNormalization/ITKColorNormalization/test/itkStructurePreservingColorNormalizationFilterTest.cxx:9: error: Header mismatch: ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) : Utilities/KWStyle/ITKHeader.h
```

**Review by Leengit — APPROVED** [review]
Thanks!

**Review by dzenanz — APPROVED** [review]
The failures seem to be due to some internet connection hiccup. I restarted the CI jobs.

**Comment by tbirdso** [comment]
Looks like Windows jobs are consistently failing to fetch the appropriate tarball, will need to investigate.

EDIT: Windows jobs seem to be successfully pulling archives now, guess there was a download issue earlier?

**Pull request merged**
